<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-14T16:16:31 IST" name="Default suite" finished-at="2023-05-14T16:17:16 IST" duration-ms="44975">
    <groups>
    </groups>
    <test started-at="2023-05-14T16:16:31 IST" name="Default test" finished-at="2023-05-14T16:17:16 IST" duration-ms="44975">
      <class name="testcases.logintestcase">
        <test-method is-config="true" signature="Beforesuite()[pri:0, instance:testcases.logintestcase@dd8ba08]" started-at="2023-05-14T16:16:31 IST" name="Beforesuite" finished-at="2023-05-14T16:16:31 IST" duration-ms="312" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Beforesuite -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:testcases.logintestcase@dd8ba08]" started-at="2023-05-14T16:16:31 IST" name="login" data-provider="testdata" finished-at="2023-05-14T16:16:52 IST" duration-ms="21190" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abhi123@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abhi456]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.commonmethods.handleassertion(commonmethods.java:15)
at testcases.logintestcase.login(logintestcase.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="close()[pri:0, instance:testcases.logintestcase@dd8ba08]" started-at="2023-05-14T16:16:52 IST" name="close" finished-at="2023-05-14T16:16:52 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:testcases.logintestcase@dd8ba08]" started-at="2023-05-14T16:16:52 IST" name="login" data-provider="testdata" finished-at="2023-05-14T16:17:16 IST" duration-ms="23737" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[vishal101@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[vi@123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.commonmethods.handleassertion(commonmethods.java:15)
at testcases.logintestcase.login(logintestcase.java:66)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="close()[pri:0, instance:testcases.logintestcase@dd8ba08]" started-at="2023-05-14T16:17:16 IST" name="close" finished-at="2023-05-14T16:17:16 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
        <test-method is-config="true" signature="Aftersuite()[pri:0, instance:testcases.logintestcase@dd8ba08]" started-at="2023-05-14T16:17:16 IST" name="Aftersuite" finished-at="2023-05-14T16:17:17 IST" duration-ms="762" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Aftersuite -->
      </class> <!-- testcases.logintestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
