<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-AAIO3JI" failures="2" tests="2" name="testcases.logintestcase" time="50.199" errors="0" timestamp="2023-03-09T16:46:52 IST" skipped="0">
  <testcase classname="testcases.logintestcase" name="login" time="25.043">
    <failure message="The following asserts failed:
	error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order&#039;s status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.commonmethods.handleassertion(commonmethods.java:15)
at testcases.logintestcase.login(logintestcase.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
  <testcase classname="testcases.logintestcase" name="login" time="25.156">
    <failure message="The following asserts failed:
	error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order&#039;s status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
error message not matching expected [Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 .] but found [New Customer
Register Account
By creating an account you will be able to shop faster, be up to date on an order's status, and keep track of the orders you have previously made.
Continue
Returning Customer
I am a returning customer
E-Mail Address
Password
Forgotten Password
Login
Register
Forgotten Password
My Account
Address Book
Wish List
Order History
Downloads
Recurring payments
Reward Points
Returns
Transactions
Newsletter]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at Resources.commonmethods.handleassertion(commonmethods.java:15)
at testcases.logintestcase.login(logintestcase.java:53)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- login -->
  <system-out/>
</testsuite> <!-- testcases.logintestcase -->
